name: Build and Deploy Resume

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX packages
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra

      - name: Build PDF
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error resume.tex
          # Run twice if necessary for references:
          pdflatex -interaction=nonstopmode -halt-on-error resume.tex

      # Commit resume.pdf back to the main branch
      - name: Commit and push resume.pdf to main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add resume.pdf
          git commit -m "Update resume.pdf [skip ci]"
          git push origin HEAD:main

      # Prepare files for GitHub Pages deployment
      - name: Prepare deployment files
        run: |
          mkdir public
          cp resume.pdf public/
          echo "resume.mateides.com" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
